### PR TITLE
test: migration to cypress

### LINKED ISSUE #6: [explorer][750 USD] Migrate e2e suite to Cypress
**About This Project**

Nightwatch is the current E2E test framework we use. It is quite old and even though it is maintained it shows its age because it is far behind other E2E frameworks, also it's based on selenium which is known to be slow and has a lot of issues if you start googling it.

One of those frameworks it's lagging behind with is https://www.cypress.io/ which provides an interactive UI that shows the actual website and flow it runs so a developer can see what exactly is happening, going wrong and take action without having to fiddle around on the live application or start to take screenshots in selenium or Nightwatch.
_See the new paper wallet at https://github.com/ArkEcosystem/paper-wallet for a project that uses TypeScript and Cypress._

> The difficulty level of this bounty is estimated as **intermediate**. The reward for completion of this project is set at **$750** (paid in ARK Ѧ).

_Requirements for completion:_
The requirements for this bounty are fairly simple. Migrate all tests from Nightwatch to Cypress without losing any coverage.
_This is the same test setup that the new paper wallet uses, and new projects based on Vue will use too as they come up._

_Necessary Skills:_
- [Cypress](https://www.cypress.io)
- [Nightwatch.js](https://nightwatchjs.org)
- [Vue.JS](https://vuejs.org)

**Applying For This Project**

To apply for this project, please read more about the process below before leaving a comment with the following:

1. A brief proposal relating to the project (e.g. Your experience, how you wish to approach the project, estimated time to completion etc.)
2. Your name and a contact email address (or another form of contact, eg. Slack username) 

**The Process**

Applicant’s will only be permitted to participate in one Tier 0 project at any one time. You can apply for as many projects as you like, but will not be eligible to be accepted until your open projects have been completed. In the meantime the projects may be awarded to other available applicants.

If your application for the project is successful we'll contact you using the details you provided, assign the project to you and mark it as in progress. You'll be required to check in regularly with the ARK team to discuss progress and development. We'll also use these updates to ensure that the PR is being completed to a satisfactory standard. If we determine that the project isn't being completed to a satisfactory standard and that this cannot be achieved with minor amends or within a satisfactory timeframe, we hold the right to dismiss the PR and reopen the project to other applicants.

To deliver the project your PR must be submitted to the respective repo. ARK repo maintainers will then leave comments and request amends if necessary. All amends requested by maintainers must be resolved before completion, and all projects must comply with our code standards and contribution guidelines (found at: https://docs.ark.io/guidebook/contribution-guidelines/). After you've submitted your project, we'll review against the brief to ensure it meets the criteria and deliverables.

Once your project is approved as complete a member of the ARK team will follow up to discuss payment. You'll need to submit an invoice and payment will be issued in (Ѧ) ARK (equivalent to the USD reward value assigned to the project), sent to an address of your choosing. We may need to request additional information regarding your identity in order to comply with our own internal Know Your Customer (KYC) guidelines.

_If you're unsuccessful in applying for this particular project, please consider applying for others. Thanks for your interest and good luck with your application!_

### LINKED ISSUE #701: [750$] Migrate e2e suite to Cypress
**About This Project**

Nightwatch is the current E2E test framework we use. It is quite old and even though it is maintained it shows its age because it is far behind other E2E frameworks, also it's based on selenium which is known to be slow and has a lot of issues if you start googling it.

One of those frameworks it's lagging behind with is https://www.cypress.io/ which provides an interactive UI that shows the actual website and flow it runs so a developer can see what exactly is happening, going wrong and take action without having to fiddle around on the live application or start to take screenshots in selenium or Nightwatch.
_See the new paper wallet at https://github.com/ArkEcosystem/paper-wallet for a project that uses TypeScript and Cypress._

> The difficulty level of this bounty is estimated as **intermediate**. The reward for completion of this project is set at **$750** (paid in ARK Ѧ).

_Requirements for completion:_
The requirements for this bounty are fairly simple. Migrate all tests from Nightwatch to Cypress without losing any coverage.
_This is the same test setup that the new paper wallet uses, and new projects based on Vue will use too as they come up._

_Necessary Skills:_
- [Cypress](https://www.cypress.io)
- [Nightwatch.js](https://nightwatchjs.org)
- [Vue.JS](https://vuejs.org)

**Applying For This Project**

To apply for this project, please read more about the process below before leaving a comment with the following:

1. A brief proposal relating to the project (e.g. Your experience, how you wish to approach the project, estimated time to completion etc.)
2. Your name and a contact email address (or another form of contact, eg. Slack username) 

**The Process**

Applicant’s will only be permitted to participate in one Tier 0 project at any one time. You can apply for as many projects as you like, but will not be eligible to be accepted until your open projects have been completed. In the meantime the projects may be awarded to other available applicants.

If your application for the project is successful we'll contact you using the details you provided, assign the project to you and mark it as in progress. You'll be required to check in regularly with the ARK team to discuss progress and development. We'll also use these updates to ensure that the PR is being completed to a satisfactory standard. If we determine that the project isn't being completed to a satisfactory standard and that this cannot be achieved with minor amends or within a satisfactory timeframe, we hold the right to dismiss the PR and reopen the project to other applicants.

To deliver the project your PR must be submitted to the respective repo. ARK repo maintainers will then leave comments and request amends if necessary. All amends requested by maintainers must be resolved before completion, and all projects must comply with our code standards and contribution guidelines (found at: https://docs.ark.io/guidebook/contribution-guidelines/). After you've submitted your project, we'll review against the brief to ensure it meets the criteria and deliverables.

Once your project is approved as complete a member of the ARK team will follow up to discuss payment. You'll need to submit an invoice and payment will be issued in (Ѧ) ARK (equivalent to the USD reward value assigned to the project), sent to an address of your choosing. We may need to request additional information regarding your identity in order to comply with our own internal Know Your Customer (KYC) guidelines.

_If you're unsuccessful in applying for this particular project, please consider applying for others. Thanks for your interest and good luck with your application!_

### PR DESCRIPTION
**Pull request by dated**
Closes #701.

**Specs**

- [x] Blocks
- [x] Block Details
- [x] Delegate Monitor
- [x] Homepage
- [x] Top Wallets
- [x] Transactions
- [x] Transaction Details
- [x] Voters
- [x] Wallet

**Configurations**

- [x] Cypress
- [x] CircleCI

## What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Refactor
- [ ] Performance
- [x] Tests
- [ ] Build
- [ ] Documentation
- [ ] Code style update
- [x] Continuous Integration
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Does this PR release a new version?

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch
- [x] All tests are passing
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by ItsANameToo** [comment]
```
Transactions should be possible to click on the recipient if it contains a link:
     CypressError: Timed out retrying: expected 'Transactions' to not equal 'Transactions'
```
:danstop:

**Comment by ItsANameToo** [comment]
Some tests I'm missing are:

- `it should refresh the confirmation count automatically` for the transaction page
- `it should be possible to see the balance` for wallet page
- `it should be possible to switch transaction type` for wallet page

But maybe you combined them like you did with the menu navigation tests

**Comment by dated** [comment]
I'll increase the timeout on that test, it works locally but takes a bit longer somehow.

`it should refresh the confirmation count automatically` is in transaction-details_spec.js, I'll add the other two tests.

**Comment by dated** [comment]
Are you happy with this @itsanametoo?

**Comment by ItsANameToo** [comment]
unhappy as it has a conflict :colbert:

**Comment by ItsANameToo** [comment]
For switching transaction types I meant this one: https://github.com/ArkEcosystem/explorer/pull/706/files#diff-112cef8c49d0b1cb9729ccd343c1377dL69 😬  (old wallet spec file, line 69)

**Comment by dated** [comment]
Oh, my bad. Will be added asap.

**Comment by dated** [comment]
Done 👌

**Review by ItsANameToo — APPROVED** [review]

**Comment by ghost** [comment]
A contributor has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by ghost** [comment]
Your pull request has been merged and marked as tier 0. _It needs a specialized, in-depth review before we can decide on its value._

**Pull request merged**
