### PR TITLE
test: adapt unit tests to new api responses and use legacy jsonwire mode in e2e tests

### PR DESCRIPTION
**Pull request by dated**
Core v2.4 slightly changes some API responses. This PR adjusts the unit tests to account for those changes.

It also sets the chromedriver mode to use the legacy jsonwire. This is a functional workaround until chromedriver has fully migrated to the W3C protocol.

## What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Refactor
- [ ] Performance
- [x] Tests
- [ ] Build
- [ ] Documentation
- [ ] Code style update
- [ ] Continuous Integration
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Does this PR release a new version?

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch
- [x] All tests are passing
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by ghost** [comment]
**Thanks for submitting this pull request!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
The [ci/circleci: test-node-10](https://circleci.com/gh/dated/ark-explorer/1239?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link) job is failing as of [31296caa864268a35fc1f9a788a74fee6bcbb9c4](https://github.com/ArkEcosystem/explorer/commit/31296caa864268a35fc1f9a788a74fee6bcbb9c4). Please [review the logs for more information](https://circleci.com/gh/dated/ark-explorer/1239?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link).

_Once you've pushed the fixes, the build will automatically re-run. Thanks!_

**Review by ItsANameToo — APPROVED** [review]

**Comment by ghost** [comment]
A contributor has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by ghost** [comment]
Your pull request has been merged and marked as tier 4. _It will earn you $10 USD._

**Pull request merged**
