### PR TITLE
feat: add tooltips to block details with the value, in currency, of amount and fees

### PR DESCRIPTION
**Pull request by dated**
## Proposed changes

Adds tooltips showing the historic value of a blocks amount and fees.

## Types of changes

- [x] New feature (non-breaking change which adds functionality)
- [x] Refactoring (improve a current implementation without adding a new feature or fixing a bug)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by ghost** [comment]
A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
The [ci/circleci: test-node-10](https://circleci.com/gh/dated/ark-explorer/1052?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link) job is failing as of [24949902b98b345961ac4e9bb1303071be0c94c8](https://github.com/ArkEcosystem/explorer/commit/24949902b98b345961ac4e9bb1303071be0c94c8). Please [review the logs for more information](https://circleci.com/gh/dated/ark-explorer/1052?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link).

_Once you've pushed the fixes, the build will automatically re-run. Thanks!_

**Comment by dated** [comment]
I didn't add the historic values to the mobile table on purpose, as to not increase loading times with a rather useless information (which is still available in the block details).

**Comment by j-a-m-l** [comment]
@dated is it ready?

**Comment by dated** [comment]
Yea.

**Comment by dated** [comment]
How's it looking @j-a-m-l?

**Review by j-a-m-l — CHANGES_REQUESTED** [review]
@dated it's triggering more than 1 time the same request to the CryptoCompare API when navigating through block pages.

To reproduce it, try navigating to an old page that it's not cached, such as 31111 or 43339.

**Comment by ghost** [comment]
Your pull request needs some changes. Please wait for a comment from one of our developers for more information.

**Review by j-a-m-l — CHANGES_REQUESTED** [review]
It's not fixed yet. When navigating to a new page which daily price isn't cached, a lot of request are triggered to fetch it from CryptoCompare.

**Comment by dated** [comment]
i see only one request per page 🤔

**Review by j-a-m-l — APPROVED** [review]
I've tried again and I haven't found any problem. Good work.

**Comment by ghost** [comment]
A member has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by ghost** [comment]
Your pull request has been merged but was not assigned a bounty tier. A maintainer will assign a bounty tier to this pull request in the next few days.

**Comment by ghost** [comment]
Your pull request has been merged and marked as tier 2. _It will earn you $50 USD._

**Pull request merged**
