### PR TITLE
refactor: close currency header immediately on change

### PR DESCRIPTION
**Pull request by kalgoop**
User won't like being stuck on the currency menu while we fetch the data. Instead, it will feel better if it closes immediately and changes in background.

## What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Refactor
- [ ] Performance
- [ ] Tests
- [ ] Build
- [ ] Documentation
- [ ] Code style update
- [ ] Continuous Integration
- [x] Other, please describe: UI Enhancement

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Does this PR release a new version?

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch
- [x] All tests are passing

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by ghost** [comment]
**Thanks for submitting this pull request!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
Your pull request doesn't follow our [contribution guidelines](https://docs.ark.io/guidebook/contribution-guidelines/). Please review and correct it.

**Comment by ghost** [comment]
The [ci/circleci: test-node-11](https://circleci.com/gh/ArkEcosystem/explorer/929?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link) job is failing as of [6e74ca5d314b31105ce9675deb4845e77e61a813](https://github.com/ArkEcosystem/explorer/commit/6e74ca5d314b31105ce9675deb4845e77e61a813). Please [review the logs for more information](https://circleci.com/gh/ArkEcosystem/explorer/929?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link).

_Once you've pushed the fixes, the build will automatically re-run. Thanks!_

**Comment by ghost** [comment]
The [ci/circleci: test-node-11](https://circleci.com/gh/ArkEcosystem/explorer/912?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link) job is failing as of [ef28a22e059409b5229f79388403d2556da8a322](https://github.com/ArkEcosystem/explorer/commit/ef28a22e059409b5229f79388403d2556da8a322). Please [review the logs for more information](https://circleci.com/gh/ArkEcosystem/explorer/912?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link).

_Once you've pushed the fixes, the build will automatically re-run. Thanks!_

**Comment by kalgoop** [comment]
Most probably the failing tests are unrelated to this PR.

**Comment by ghost** [comment]
Your pull request has been merged and marked as tier 5. _It will earn you $5 USD._

**Pull request merged**
