### PR TITLE
fix: handle wallet attributes of new api response

### LINKED ISSUE #854: bug: 2nd sig / multisig indication
The API response recently changed, so 2nd signature is now part of an `attributes` object on a wallet. Because of this, 2nd signature addresses no longer have the `lock` icon at the top (see https://dexplorer.ark.io/wallets/D5xRcwzEGSN83nyuGN74Sw8f353vDmm2tt). Similar for multisig addresses

### PR DESCRIPTION
**Pull request by dated**
## Summary

Fixes #854.

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [ ] Ready to be merged

### CODE REVIEW

**Comment by ghost** [comment]
**Thanks for submitting this pull request!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by dated** [comment]
Closing as the underlying issue will be fixed on the API side of things.

**Comment by ghost** [comment]
Your pull request has been closed, thank you for trying to solve an issue. If you think it was closed prematurely please provide additional information.

**Comment by leMaur** [comment]
@alfonsobries It seems good to me! 👍🏽

**Pull request closed without merging**
