### PR TITLE
refactor: get htlcEnabled from config

### LINKED ISSUE #831: refactor: hide HTLC features if not enabled
When HTLC is not enabled on the network, the related features should be hidden from explorer (e.g. the `Locks` tab for a wallet, can't recall if anything else currently caters for locks 🤔 `LinkWallet` can be left as it would only show timelocks if they would match the transaction type anyway)

Can look into milestones and whether is has one for enabling htlc: 
https://github.com/ArkEcosystem/core/blob/develop/packages/crypto/src/networks/devnet/milestones.json#L87

### PR DESCRIPTION
**Pull request by dated**
## Summary

Closes #831.

## Checklist

- [ ] Documentation _(if necessary)_
- [x] Tests _(if necessary)_
- [x] Ready to be merged

### CODE REVIEW

**Comment by dated** [comment]
I'll create some more businesses and bridgechains later on so the tests can pass again in absence of a mirage server :lala:

**Comment by ItsANameToo** [comment]
or you could take on the mirage server T0 :lel:

**Review by ItsANameToo — APPROVED** [review]

**Comment by ghost** [comment]
A member has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by dated** [comment]
Something unrelated is failing.

```
FAIL __tests__/unit/specs/services/transaction.spec.ts (50.715s)
  ● Services > Transaction › should return and empty list if no transactions in a block
```

**Comment by ItsANameToo** [comment]
yeah it runs into a timeout for some reason 🤔

**Comment by ghost** [comment]
Your pull request has been merged and marked as tier 4. _It will earn you $20 USD._

**Pull request merged**
