### PR TITLE
fix: table column sorting

### LINKED ISSUE #562: sorting of the delegates table not working on nested properties
**Describe the bug**
The sorting of nested properties such as the forged blocks count or productivity is currently not working. Will be fixed asap.

### PR DESCRIPTION
**Pull request by dated**
## Proposed changes

Fixes #562, all tables were affected.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] Refactoring (improve a current implementation without adding a new feature or fixing a bug)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by ghost** [comment]
@dated Thanks for submitting this pull request, a maintainer will get back to you shortly!

**Comment by ghost** [comment]
@alexbarnsley @faustbrian @luciorubeens - please review this in the next few days. Be sure to explicitly select labels so I know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
@dated The [ci/circleci: test-node-stable](https://circleci.com/gh/dated/ark-explorer/870?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link) job is failing as of [2ea85911237b1c2159d580d7985a24b53598d493](https://github.com/ArkEcosystem/explorer/commit/2ea85911237b1c2159d580d7985a24b53598d493). Please [review the logs for more information](https://circleci.com/gh/dated/ark-explorer/870?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link).

_Once you've pushed the fixes, the build will automatically re-run. Thanks!_

**Review by faustbrian — APPROVED** [review]

**Comment by ghost** [comment]
@dated A contributor has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by ghost** [comment]
@dated Your pull request has been merged but was not assigned a bounty tier. @alexbarnsley @faustbrian @luciorubeens - please assign a bounty tier to this pull request in the next few days.

**Comment by ghost** [comment]
@dated Your pull request has been merged and marked as tier 4. _It will earn you $10 USD._

**Pull request merged**
