### PR TITLE
refactor: replace vue-table-component with vue-good-table

### LINKED ISSUE #640: Replace vue-table-component with vue-good-table

### PR DESCRIPTION
**Pull request by dated**
Closed #640.

## What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Refactor
- [ ] Performance
- [ ] Tests
- [ ] Build
- [ ] Documentation
- [ ] Code style update
- [ ] Continuous Integration
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Does this PR release a new version?

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch
- [x] All tests are passing
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by ghost** [comment]
**Thanks for submitting this pull request!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
The [ci/circleci: test-node-11](https://circleci.com/gh/dated/ark-explorer/1303?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link) job is failing as of [84783802b073521b44a82fba95840558b3cc6aaf](https://github.com/ArkEcosystem/explorer/commit/84783802b073521b44a82fba95840558b3cc6aaf). Please [review the logs for more information](https://circleci.com/gh/dated/ark-explorer/1303?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link).

_Once you've pushed the fixes, the build will automatically re-run. Thanks!_

**Comment by ItsANameToo** [comment]
The smartbridge field in the table no longer gets hidden at the correct time (on the transaction screens). It gets removed at 1024px now when it already doesn't fit the screen anymore (on current explorer it's at 1100px instead)

Other than that it seems to work nicely! Sorting works as intended and haven't seen any other anomalies

**Review by ItsANameToo — APPROVED** [review]

**Comment by ghost** [comment]
A contributor has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by ghost** [comment]
Your pull request has been merged and marked as tier 3. _It will earn you $25 USD._

**Pull request merged**
