### PR TITLE
fix: vendorfield overflow

### LINKED ISSUE #617: bug: smartbridge text overflow
**Describe the bug**
With the new 255 smartbridge field, it can overflow if there are no spaces in the text: https://dexplorer.ark.io/transaction/4a9f883adae40c0af85635df7ac306ce530bc6a54f564fb2bc00c3fb2d6421ba . Can probably be fixed by adding `word-break: break-word` to the fields where a smartbridge text can be shown.

**To Reproduce**
See here: https://dexplorer.ark.io/transaction/4a9f883adae40c0af85635df7ac306ce530bc6a54f564fb2bc00c3fb2d6421ba

**Expected behavior**
It should break the text so it doesn't overflow

**Screenshots**
-

**Server (please complete the following information):**
-

**Additional context**
-

### PR DESCRIPTION
**Pull request by dated**
## Proposed changes

Closes #617 and adjusts the table margins and overflows.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build (changes that affect the build system)
- [ ] Docs (documentation only changes)
- [ ] Test (adding missing tests or fixing existing tests)
- [ ] Other... Please describe:

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by ghost** [comment]
**Thanks for submitting this pull request!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ItsANameToo** [comment]
@dated nice, can you also add it to the tooltip?

image

**Comment by ItsANameToo** [comment]
awesome

**Review by ItsANameToo — APPROVED** [review]

**Comment by ghost** [comment]
A contributor has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by ghost** [comment]
Your pull request has been merged and marked as tier 4. _It will earn you $10 USD._

**Pull request merged**
