### PR TITLE
refactor: i18n module

### PR DESCRIPTION
**Pull request by dated**
Major refactor of the i18n module to add hierarchy to the translation messages.

## What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Refactor
- [ ] Performance
- [ ] Tests
- [ ] Build
- [ ] Documentation
- [ ] Code style update
- [ ] Continuous Integration
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Does this PR release a new version?

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch
- [x] All tests are passing
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by ghost** [comment]
**Thanks for submitting this pull request!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ItsANameToo** [comment]
some conflicts 🤔

**Comment by dated** [comment]
yes yes ...

**Comment by ItsANameToo** [comment]
Seeing this in the console when I had a previous language selected (from an older version):

image

I assume people that were on older locales will all fall back to english after we update with this?

**Comment by dated** [comment]
Correct, I should probably add something that sets the updated language key.

**Comment by dated** [comment]
The language key is now being set to the new format @ItsANameToo, see 54301f7d51e860caaebfc0be14b817534491fafe for reference.

**Review by ItsANameToo — APPROVED** [review]

**Comment by ghost** [comment]
A contributor has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by ghost** [comment]
Your pull request has been merged and marked as tier 3. _It will earn you $50 USD._

**Comment by ItsANameToo** [comment]
@alfonsobries can be updated to make use of 1.2.16

**Pull request merged**
