### PR TITLE
fix: do not censor floats in vendorfield

### PR DESCRIPTION
**Pull request by dated**
## Summary

Floats in a vendorfield are recognized as urls by the sanitizer and thus censored, e.g. https://dexplorer.ark.io/transaction/fe9150ed52b3dd693df8f38f443c0984e4b5baf65bfda694cf6a5d656911dd1a

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [x] Ready to be merged

### CODE REVIEW

**Comment by ghost** [comment]
**Thanks for submitting this pull request!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by dated** [comment]
Can you re-run the actions @itsanametoo?

**Comment by ItsANameToo** [comment]
I did, but there's still something going wrong where it can't check out the branch

**Comment by ghost** [comment]
Your pull request has been closed, thank you for trying to solve an issue. If you think it was closed prematurely please provide additional information.

**Pull request closed without merging**
