### PR TITLE
fix: fetch delegates only when network height is available & refactoring

### PR DESCRIPTION
**Pull request by dated**
## Proposed changes

When visiting the delegate monitor directly the statuses are not calculated correctly and all delegates are red for a short amount of time, which is caused by the network height not being available yet.

Also updates some vue packages and the usage of the link-wallet component.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] Refactoring (improve a current implementation without adding a new feature or fixing a bug)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by ghost** [comment]
**Thanks for submitting this pull request!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by dated** [comment]
The confirmations suffer from the same bug, I'll add a fix to https://github.com/ArkEcosystem/explorer/pull/581 which refactors the transaction page already.

**Comment by dated** [comment]
`etifix`?

**Comment by luciorubeens** [comment]
Weird, I just changed the label 🤔

**Review by luciorubeens — APPROVED** [review]

**Comment by ghost** [comment]
A member has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by ghost** [comment]
Your pull request has been merged and marked as tier 4. _It will earn you $10 USD._

**Pull request merged**
