### PR TITLE
chore: add Altilly Exchange Wallet

### PR DESCRIPTION
**Pull request by NayiemW**
## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build (changes that affect the build system)
- [ ] Docs (documentation only changes)
- [ ] Test (adding missing tests or fixing existing tests)
- [ ] Other... Please describe:

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by ghost** [comment]
**Thanks for submitting this pull request!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
Your pull request doesn't follow our [contribution guidelines](https://docs.ark.io/guidebook/contribution-guidelines/). Please review and correct it.

**Review by faustbrian — APPROVED** [review]

**Comment by ghost** [comment]
A contributor has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by ghost** [comment]
Your pull request has been merged and marked as tier 5. _It will earn you $5 USD._

**Comment by ItsANameToo** [comment]
@samharperpittam did you check if this is also an issue with the changes in #592 ? as that adds a hover color to some tables (but if it's limited to delegate tables then we won't see it as those don't have this 2-circle-component thingy)

**Comment by samharperpittam** [comment]
> @samharperpittam did you check if this is also an issue with the changes in #592 ? as that adds a hover color to some tables (but if it's limited to delegate tables then we won't see it as those don't have this 2-circle-component thingy)

I didn't see any similar issues on https://github.com/ArkEcosystem/explorer.ark.io/pull/592 as it's just limited to the Delegate and Delegate Monitor pages.

**Pull request merged**
