### PR TITLE
fix/refactor: pagination issues, voter count & voters

### LINKED ISSUE #574: Missing delegate voters
https://explorer.ark.io/wallets/AUycoaAHjReb1iYtGe4qWH5v7MJ95sjkvZ/voters/1. It's a little weird, AeWqqVnmStrrpibq1bqeFwM5Tp97kJupsA not showing.

---
This issue was created by `@vul`.

### PR DESCRIPTION
**Pull request by dated**
## Proposed changes

Fixes #574, #569, #563.

However, without [ArkEcosystem/core#2103](https://github.com/ArkEcosystem/core/pull/2103) the shown voters won't be fetched in the correct order.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] Refactoring (improve a current implementation without adding a new feature or fixing a bug)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by ghost** [comment]
@dated Thanks for submitting this pull request, a maintainer will get back to you shortly!

**Comment by ghost** [comment]
@alexbarnsley @faustbrian @luciorubeens - please review this in the next few days. Be sure to explicitly select labels so I know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by dated** [comment]
I'll integrate https://github.com/ArkEcosystem/explorer/pull/565 into this PR since they are sort of intertwined.

**Comment by dated** [comment]
any development on this? :)

**Review by j-a-m-l — APPROVED** [review]
I haven't detected anything faiing.

Thanks @dated

**Comment by ghost** [comment]
@dated A member has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by ghost** [comment]
@dated Your pull request has been merged but was not assigned a bounty tier. @alexbarnsley @faustbrian @luciorubeens - please assign a bounty tier to this pull request in the next few days.

**Comment by ghost** [comment]
@dated Your pull request has been merged and marked as tier 3. _It will earn you $25 USD._

**Pull request merged**
