### PR TITLE
fix: failing tests

### PR DESCRIPTION
**Pull request by ItsANameToo**
Fixing now-failing tests because of core 2.6 moving to mainnet

### CODE REVIEW

**Comment by alfonsobries** [comment]
sorry @leMaur forget to assign myself 😅

**Comment by leMaur** [comment]
> sorry @leMaur forget to assign myself 😅

@alfonsobries 😆 no worry!

**Comment by alexbarnsley** [comment]
@alfonsobries FYI I've asked Oleg to confirm designs for this as they haven't been updated

**Comment by alfonsobries** [comment]
@alexbarnsley yep the design seems the same, but the extra padding on the buttons increased the space between buttons, 

Dev branch: (about 33 px between separator and search icon)
image

This PR: (about 37px between separator and search icon)
image


vv
image

**Comment by alexbarnsley** [comment]
Updated based on the designs Oleg has done. They can be found on Figma on the "Home page and Search page" page

image

**Pull request merged**
