### PR TITLE
refactor: migrate remaining components to typescript

### PR DESCRIPTION
**Pull request by dated**
## Summary

Migrates the remaining components to typescript,

- [x] `App`
- [x] `QrCode`
- [x] `TableWrapper`
- [x] `ToggleLanguage`

Proper type definitions for `vue-good-table` are out of scope and should be submitted to DefinitelyTyped imho.

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [x] Ready to be merged

### CODE REVIEW

**Comment by ItsANameToo** [comment]
I'm seeing this on wallet pages: `[Vue warn]: Invalid default value for prop "sortQuery": Props with type Object/Array must use a factory function to return the default value.`

Other small tweaks, this icon on the delegate monitor is no longer blue (probably from a previous PR :trollface: ):
image

**Comment by dated** [comment]
Fixed & fixed, that icon must have slipped through - I didn't find any others with the wrong color.

**Comment by dated** [comment]
GitHub actions are now broken, sad.

**Comment by ItsANameToo** [comment]
When you check a wallet and sort on a property, this is not saved throughout a refresh. Out of scope for this PR as it's not because of your changes, but I think you'd be interested in knowing it :trollface:

**Review by ItsANameToo — APPROVED** [review]

**Comment by ghost** [comment]
A contributor has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by ghost** [comment]
Your pull request has been merged and marked as tier 4. _It will earn you $20 USD._

**Pull request merged**
