### PR TITLE
fix: handle undefined delegate rank

### PR DESCRIPTION
**Pull request by dated**
A delegate that has registered in the current round is not assigned a rank, this PR handles the case where the `rank` property is not available.

## What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactor
- [ ] Performance
- [ ] Tests
- [ ] Build
- [ ] Documentation
- [ ] Code style update
- [ ] Continuous Integration
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Does this PR release a new version?

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch
- [ ] All tests are passing
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by ghost** [comment]
**Thanks for submitting this pull request!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
The [ci/circleci: test-node-11](https://circleci.com/gh/dated/ark-explorer/1231?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link) job is failing as of [f1319e4a90b42af90306d1ffe6d3af0a502d6edd](https://github.com/ArkEcosystem/explorer/commit/f1319e4a90b42af90306d1ffe6d3af0a502d6edd). Please [review the logs for more information](https://circleci.com/gh/dated/ark-explorer/1231?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link).

_Once you've pushed the fixes, the build will automatically re-run. Thanks!_

**Comment by dated** [comment]
i'll adjust the tests asap

**Comment by ItsANameToo** [comment]
Failing unit test because of the `not yet available` text @dated

**Comment by ItsANameToo** [comment]
You're quick 😂

**Comment by dated** [comment]
it's the same errors as #636 now. newer versions or selenium and nightwatch don't fix those.

**Comment by ghost** [comment]
Your pull request has been merged and marked as tier 4. _It will earn you $10 USD._

**Comment by faustbrian** [comment]
CI is failing after a frontend dependency update.

**Pull request merged**
