### PR TITLE
fix: add shadows to dark-theme and fix dark style of dropdowns

### PR DESCRIPTION
**Pull request by dated**
This PR enables shadows when using the dark theme and styles the dropdowns accordingly.

It also:

- cleans up the wallet transactions component
- casts the page number to number type where it was not done yet
- adds a top padding to the market chart to avoid cropped hover circles

  image

## What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [x] Refactor
- [ ] Performance
- [ ] Tests
- [ ] Build
- [ ] Documentation
- [ ] Code style update
- [ ] Continuous Integration
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Does this PR release a new version?

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch
- [x] All tests are passing
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by ghost** [comment]
**Thanks for submitting this pull request!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Review by ItsANameToo — APPROVED** [review]

**Comment by ghost** [comment]
A contributor has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by ghost** [comment]
Your pull request has been merged and marked as tier 4. _It will earn you $20 USD._

**Comment by alexbarnsley** [comment]
@alfonsobries there's also the filter used above certain tables:

https://github.com/ArkEcosystem/explorer.ark.io/blob/feat/remove-AIP36-filters/resources/views/components/transaction-table-filter.blade.php#L43-L83

**Edit:** Search works though which is good! Just this area needs updating

image

**Comment by alfonsobries** [comment]
@alexbarnsley ready to be reviewed again

**Comment by alfonsobries** [comment]
@alexbarnsley ✅

**Pull request merged**
