### PR TITLE
feat: show icon if wallet is known

### PR DESCRIPTION
**Pull request by dated**
## Proposed changes

Implements https://github.com/ArkEcosystem/explorer/issues/528.

icon

address

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [ ] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by dated** [comment]
Changed the tooltip to `This is a verified address` as @ItsANameToo is doing on https://github.com/ArkEcosystem/desktop-wallet/pull/881.

**Comment by ItsANameToo** [comment]
:hide:

**Comment by ItsANameToo** [comment]
fyi: Oleg is creating an icon for it. @alexbarnsley is no designer so we shouldn't listen to what he thinks is fine 😬

**Comment by dated** [comment]
Send it over once you get it please :trollface:

**Pull request merged**
