### PR TITLE
chore: tailwindcss major version update (v1.0.4)

### LINKED ISSUE #627: Upgrade to the latest tailwindcss version
Tailwind should be upgraded to the latest v1.0.x version. Details can be found in their [upgrade guide](https://tailwindcss.com/docs/upgrading-to-v1)

### PR DESCRIPTION
**Pull request by dated**
- Update tailwindcss to 1.x (closes #627)
- Split stylesheet into modules
- Remove Node 10 from tests

## What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Refactor
- [ ] Performance
- [ ] Tests
- [ ] Build
- [ ] Documentation
- [ ] Code style update
- [ ] Continuous Integration
- [x] Other, please describe: dependencies

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Does this PR release a new version?

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch
- [ ] All tests are passing
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by ghost** [comment]
**Thanks for submitting this pull request!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
The [ci/circleci: test-node-11](https://circleci.com/gh/dated/ark-explorer/1282?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link) job is failing as of [b6c9718b600d781290d7d2ef2de73f3f2040edfe](https://github.com/ArkEcosystem/explorer/commit/b6c9718b600d781290d7d2ef2de73f3f2040edfe). Please [review the logs for more information](https://circleci.com/gh/dated/ark-explorer/1282?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link).

_Once you've pushed the fixes, the build will automatically re-run. Thanks!_

**Comment by dated** [comment]
checking.

**Comment by ItsANameToo** [comment]
"fixed" :trollface:

**Comment by dated** [comment]
checking again :colbert:

**Comment by dated** [comment]
fixed @ItsANameToo

**Comment by dated** [comment]
Can you take a look when you have a few minutes @ItsANameToo? #640 requires some changes to the stylesheets, I'd prefer not having to deal with merge conflicts :trollface:

**Comment by ItsANameToo** [comment]
yeah my bad, will take a look tonight

**Comment by ItsANameToo** [comment]
Looks good overall, just some small things I noticed:

- h1 tags (e.g. `latest transactions` on homepage) are no longer bold
- delegate monitor status circle is no longer centered
- this could be me, but opening the QR code no longer seems to "fade in" anymore? :thinking:

**Comment by dated** [comment]
I'll fix in the morning, thanks for checking.

**Comment by dated** [comment]
I fixed the three issues above and another minor bug where the delegate monitor would briefly display `No results` before showing the loader.

**Review by ItsANameToo — APPROVED** [review]

**Comment by ghost** [comment]
A contributor has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by ghost** [comment]
Your pull request has been merged and marked as tier 2. _It will earn you $50 USD._

**Pull request merged**
