### PR TITLE
feat: extended pagination

### PR DESCRIPTION
**Pull request by dated**
Implements #666.

image

## What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Refactor
- [ ] Performance
- [ ] Tests
- [ ] Build
- [ ] Documentation
- [ ] Code style update
- [ ] Continuous Integration
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Does this PR release a new version?

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch
- [ ] All tests are passing
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by dated** [comment]
why is codacy even looking there?

```
---
exclude_paths:
  - '__mocks__/**/*'
  - '__tests__/**/*'
  - 'src/styles/**/*'
  - '*.md'
```

:danwhat:

**Comment by ItsANameToo** [comment]
Niiiice, just a couple thing (functionality wise, will check code in a minute):

1) Can you add `type="number"` to the search input so letters aren't allowed? 
2) For some reason I don't have a `first` button on mobile:
image 
(ok figured this one out, it appears from page 5 onwards, but on  mobile it should be available from page 2 onwards)

3) design also had a search icon here:
image
without it it only works by pressing enter,  but I'm not sure if everyone will understand that

4) light button background should be #e5f0f9 🤔 but since you use the default button color I'll check with Oleg if they should all have that color so you can just change the `--theme-button` var in that case
5) the `active` color for the selected page in light mode should be `#c5dbed` (you're like 1 number off :trollface: )

**Comment by ItsANameToo** [comment]
regarding 4); change the var to `#e5f0f9` 👍

**Comment by dated** [comment]
I'll try to get it done tonight, thanks for the feedback!

**Comment by dated** [comment]
All issues should be resolved now 👀 @ItsANameToo

**Comment by ItsANameToo** [comment]
as discussed, only issue is this: 
image (12)

**Comment by ItsANameToo** [comment]
🎉

**Review by ItsANameToo — APPROVED** [review]

**Comment by ghost** [comment]
A contributor has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by ghost** [comment]
Your pull request has been merged and marked as tier 2. _It will earn you $100 USD._

**Pull request merged**
