### PR TITLE
fix: word-break in transaction table

### PR DESCRIPTION
**Pull request by dated**
## Proposed changes

Large characters in the vendorfield column can cause the table row to be out of bounds.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build (changes that affect the build system)
- [ ] Docs (documentation only changes)
- [ ] Test (adding missing tests or fixing existing tests)
- [ ] Other... Please describe:

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by ghost** [comment]
**Thanks for submitting this pull request!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Review by ItsANameToo — DISMISSED** [review]

**Comment by ghost** [comment]
A contributor has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by ItsANameToo** [comment]
interestingly tailwind has a `break-all` that sets `word-break: normal` 🤔

**Comment by dated** [comment]
yep :danwhat:

**Comment by ItsANameToo** [comment]
Seems an issue with their docs tho:

image

can you change it to use `break-all` instead of your custom class?

**Comment by dated** [comment]
As discussed in DM, the `.break-all` class was added in `v1.0.0-beta.1`, which also requires fundamental changes to the tailwindcss configuration, see [v1.0.0-beta.1 (Upgrade Guide)](https://github.com/tailwindcss/tailwindcss/releases/tag/v1.0.0-beta.1) for reference.

**Review by ItsANameToo — APPROVED** [review]

**Comment by ghost** [comment]
A contributor has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by ghost** [comment]
Your pull request has been merged and marked as tier 5. _It will earn you $5 USD._

**Comment by alessiodf** [comment]
This appears to have caused some issues with some vendorfields now spanning multiple lines in Safari and Chrome:

Screenshot 2019-05-25 at 22 20 46

**Comment by ItsANameToo** [comment]
Good catch, should be fixed in #626

**Pull request merged**
