### PR TITLE
YYYY.MM.DD instead of opposite

### PR DESCRIPTION
**Pull request by tpscrpt**
## Proposed changes

In general, the American date format is only really intuitive to Americans in America. When any internationalization occurs, Americans themselves tend to adapt to the date format quite easily, especially if it's in YYYY.MM.DD format and the following is HH:mm:ss. The only reason I know is because I'm an inbetweener! :canada: (culture here is weird).

This PR just changes the standard getReadableTimestamp mixin to display timestamps from bigger to smaller unit.

#349 raises this issue, probably could use a timezone selection tool regardless.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build (changes that affect the build system)
- [ ] Docs (documentation only changes)
- [ ] Test (adding missing tests or fixing existing tests)
- [ ] Other... Please describe:

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/developers/guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by dated** [comment]
You can use `.format('L LTS')` to get a localized timestamp, see [https://momentjs.com/#multiple-locale-support](https://momentjs.com/#multiple-locale-support). But the language always falls back to english apparently. The App tries to get the language from `localStorage('language')` which is never set in the language setter method of the [ui store](https://github.com/ArkEcosystem/explorer/blob/master/src/store/modules/ui.js#L30).

``` javascript
# App.vue

this.$store.dispatch(
  'ui/setLanguage',
  localStorage.getItem('language') || 'en'
)
```

 You can probably use `navigator.language` to get the proper localisation, which has to be set in moment through `moment.locale(store.getters['ui/language'])`.

**Comment by tpscrpt** [comment]
@dated I'm not a vue developer and not familiar with moment, but will give it a try.

**Comment by faustbrian** [comment]
As @dated said it is better to localise the timestamp if we already change it rather then just using the American format which is not used anywhere else.

**Comment by tpscrpt** [comment]
not interested in fixing this anymore, my apologies. Still do think that the biggest to lowest unit approach is better than the American default

**Pull request closed without merging**
