### PR TITLE
[WIP] fix: hide marketcap when no currency

### PR DESCRIPTION
**Pull request by alexbarnsley**
Market cap shows for bridgechains as 1 to 1 with ARK, which is wrong. This hides the market cap entirely if no currency is set.

## What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactor
- [ ] Performance
- [ ] Tests
- [ ] Build
- [ ] Documentation
- [ ] Code style update
- [ ] Continuous Integration
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Does this PR release a new version?

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch
- [ ] All tests are passing
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by ghost** [comment]
The [ci/circleci: test-node-10](https://circleci.com/gh/ArkEcosystem/explorer/959?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link) job is failing as of [23eca9ee2733561b465cdc17b38516c488412e8a](https://github.com/ArkEcosystem/explorer/commit/23eca9ee2733561b465cdc17b38516c488412e8a). Please [review the logs for more information](https://circleci.com/gh/ArkEcosystem/explorer/959?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link).

_Once you've pushed the fixes, the build will automatically re-run. Thanks!_

**Comment by alexbarnsley** [comment]
On hold, so @ItsANameToo can take a look at the failing e2e test since I don't have a clue

**Comment by dated** [comment]
The tests should pass just fine, probably just a timeout. The mobile view however needs adjustments.

**Comment by ItsANameToo** [comment]
Not stale, just ignored 😄 I had a question about it @alexbarnsley, see slack

**Comment by faustbrian** [comment]
@ItsANameToo 🐗

**Comment by ItsANameToo** [comment]
Getting to it soon :colbert:

**Review by ItsANameToo — APPROVED** [review]

**Pull request merged**
