### PR TITLE
feat: advanced search page

### PR DESCRIPTION
**Pull request by dated**
[WIP]

## What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Refactor
- [ ] Performance
- [ ] Tests
- [ ] Build
- [ ] Documentation
- [ ] Code style update
- [ ] Continuous Integration
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Does this PR release a new version?

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch
- [ ] All tests are passing
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by ghost** [comment]
The [ci/circleci: test-node-11](https://circleci.com/gh/dated/ark-explorer/1297?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link) job is failing as of [bc671437f9a0f957ac29d85daf438416d706aa81](https://github.com/ArkEcosystem/explorer/commit/bc671437f9a0f957ac29d85daf438416d706aa81). Please [review the logs for more information](https://circleci.com/gh/dated/ark-explorer/1297?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link).

_Once you've pushed the fixes, the build will automatically re-run. Thanks!_

**Comment by ItsANameToo** [comment]
What's the state on this?

**Comment by dated** [comment]
Will get back to it next.

**Comment by ghost** [comment]
Your pull request has been closed, thank you for trying to solve an issue. If you think it was closed prematurely please provide additional information.

**Pull request closed without merging**
