### PR TITLE
fix: copy button on iOS

### PR DESCRIPTION
**Pull request by marekhoeven**
## Proposed changes
A possible solution to issue #532 
A workaround for iOS devices where copy is not supported on mobile devices. 

## Types of changes
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build (changes that affect the build system)
- [ ] Docs (documentation only changes)
- [ ] Test (adding missing tests or fixing existing tests)
- [ ] Other... Please describe:

## Checklist
- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Further comments
I'm not sure how to add appropriate tests that would prove the fix on iOS, I started a ngrok-service to check my local-server changes on my mobile (iOS 12, iPhone XS)

### CODE REVIEW

**Comment by ghost** [comment]
**Thanks for submitting this pull request!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
Your pull request doesn't follow our [contribution guidelines](https://docs.ark.io/guidebook/contribution-guidelines/). Please review and correct it.

**Comment by ghost** [comment]
The [ci/circleci: test-node-stable](https://circleci.com/gh/ArkEcosystem/explorer/762?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link) job is failing as of [248a254d8a702cbfd7e225b1a1cf54791f22483b](https://github.com/ArkEcosystem/explorer/commit/248a254d8a702cbfd7e225b1a1cf54791f22483b). Please [review the logs for more information](https://circleci.com/gh/ArkEcosystem/explorer/762?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link).

_Once you've pushed the fixes, the build will automatically re-run. Thanks!_

**Comment by ghost** [comment]
The [ci/circleci: test-node-stable](https://circleci.com/gh/ArkEcosystem/explorer/762?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link) job is failing as of [248a254d8a702cbfd7e225b1a1cf54791f22483b](https://github.com/ArkEcosystem/explorer/commit/248a254d8a702cbfd7e225b1a1cf54791f22483b). Please [review the logs for more information](https://circleci.com/gh/ArkEcosystem/explorer/762?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link).

_Once you've pushed the fixes, the build will automatically re-run. Thanks!_

**Review by j-a-m-l — CHANGES_REQUESTED** [review]
Tested on iOS 12.2 by @sleepdefic1t.

I didn't detect any problem on other browsers.

I'd make only some changes: use `const` instead of `let` when possible.

**Comment by j-a-m-l** [comment]
@marekhoeven replace the `let` statements inside the `if` block. Move also the `isiOSDevice` before or after `textArea`, to keep _concepts_ together.

**Review by j-a-m-l — APPROVED** [review]
Thanks @marekhoeven

**Comment by ghost** [comment]
A member has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by ghost** [comment]
Your pull request has been merged and marked as tier 4. _It will earn you $10 USD._

**Pull request merged**
