### PR TITLE
ci: switch to codecov-action

### PR DESCRIPTION
**Pull request by dated**
## Summary

Use the [codecov-action](https://github.com/codecov/codecov-action) instead of including codecov as a dependency.

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [x] Ready to be merged

### CODE REVIEW

**Comment by ghost** [comment]
**Thanks for submitting this pull request!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
Your pull request has been closed, thank you for trying to solve an issue. If you think it was closed prematurely please provide additional information.

**Comment by ghost** [comment]
This pull-request has now been re-opened. If applicable please provide additional information as requested by one of the reviewers.

**Comment by dated** [comment]
The tests failed because I deleted the branch during the run - they will pass just fine if retriggered.

**Comment by ItsANameToo** [comment]
why would you do that :colbert:

**Review by ItsANameToo — APPROVED** [review]

**Comment by ghost** [comment]
A member has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by ghost** [comment]
Your pull request has been merged but was not assigned a bounty tier. A maintainer will assign a bounty tier to this pull request in the next few days.

**Comment by dated** [comment]
> why would you do that :colbert:

I was testing something with the `CODECOV_TOKEN`, which failed. I figured switching to codecov-action was worthwhile anyway only after the fact.

**Comment by ghost** [comment]
Your pull request has been merged. Thank you for your contribution to the ARK Ecosystem.

**Pull request merged**
