### PR TITLE
chore: update ACF address

### PR DESCRIPTION
**Pull request by dated**
## Proposed changes

https://explorer.ark.io/wallets/AagJoLEnpXYkxYdYkmdDSNMLjjBkLJ6T67

## Types of changes

- [x] Other... Please describe: chore

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by ghost** [comment]
**Thanks for submitting this pull request!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by j-a-m-l** [comment]
To have a reference of the older wallet, I'd keep it, but renamed to "Ark Community Fund (old)" or something similar.

**Comment by dated** [comment]
🤔

I'd rename it to `ACF Hot Wallet (old)` then and the new one to `ACF Hot Wallet`. There were a bunch of old ACF wallets and i guess there will be a bunch again soon, which i'd name `ACF Wallet xx` then.

**Comment by j-a-m-l** [comment]
OK, would you mind to add them all of the previous too?

**Comment by dated** [comment]
There were no outgoing payments from these wallets, imho it doesn't make much sense to add them. The ACF will potentially redistribute their votes with every term or more often. Adding all these wallets will grow the list of known wallets unnecessarily.

**Review by j-a-m-l — APPROVED** [review]

**Comment by ghost** [comment]
A member has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by ghost** [comment]
Your pull request has been merged but was not assigned a bounty tier. A maintainer will assign a bounty tier to this pull request in the next few days.

**Comment by ghost** [comment]
Your pull request has been merged and marked as tier 4. _It will earn you $10 USD._

**Pull request merged**
