### PR TITLE
fix: balance tooltip position

### PR DESCRIPTION
**Pull request by dated**
Fixes the position of the balance tooltip.

image

## What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactor
- [ ] Performance
- [ ] Tests
- [ ] Build
- [ ] Documentation
- [ ] Code style update
- [ ] Continuous Integration
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Does this PR release a new version?

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch
- [x] All tests are passing
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by ghost** [comment]
**Thanks for submitting this pull request!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
The [ci/circleci: test-node-11](https://circleci.com/gh/dated/ark-explorer/1293?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link) job is failing as of [0286597ad084c441a5673752d4bae4f5d81bd697](https://github.com/ArkEcosystem/explorer/commit/0286597ad084c441a5673752d4bae4f5d81bd697). Please [review the logs for more information](https://circleci.com/gh/dated/ark-explorer/1293?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link).

_Once you've pushed the fixes, the build will automatically re-run. Thanks!_

**Comment by ItsANameToo** [comment]
why does test-node-10 not report its status 😭

**Comment by ghost** [comment]
Your pull request has been merged and marked as tier 5. _It will earn you $5 USD._

**Pull request merged**
