### PR TITLE
chore(deps): bump lodash.defaultsdeep from 4.6.0 to 4.6.1

### PR DESCRIPTION
**Pull request by faustbrian**
Bumps [lodash.defaultsdeep](https://github.com/lodash/lodash) from 4.6.0 to 4.6.1.
- [Release notes](https://github.com/lodash/lodash/releases)
- [Commits](https://github.com/lodash/lodash/compare/4.6.0...4.6.1)

Signed-off-by: dependabot[bot] <support@github.com>

### CODE REVIEW

**Comment by ItsANameToo** [comment]
throws me an error when I visit a wallet page as it can't create the QR modal @alfonsobries 
image

**Comment by alfonsobries** [comment]
@ItsANameToo just found the problem, to fix it ill also need this to be released https://github.com/ArkEcosystem/laravel-ui/pull/138

**Comment by alfonsobries** [comment]
@ItsANameToo ready

**Comment by ItsANameToo** [comment]
@alfonsobries your change breaks the button positioning as they used to take equal widths: 
image

I'll fix it to get it merged

**Pull request merged**
