### PR TITLE
fix: mobile blocks table and standby delegate approval tooltip

### PR DESCRIPTION
**Pull request by dated**
## Proposed changes

Fixes the mobile blocks table where the forged amount and fees were missing.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by ghost** [comment]
@dated Thanks for submitting this pull request, a maintainer will get back to you shortly!

**Comment by ghost** [comment]
@alexbarnsley @faustbrian @luciorubeens - please review this in the next few days. Be sure to explicitly select labels so I know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
@dated The [ci/circleci: test-node-stable](https://circleci.com/gh/dated/ark-explorer/935?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link) job is failing as of [7595d395b3ecaf4bf28c884f1dc7cf3459310d7c](https://github.com/ArkEcosystem/explorer/commit/7595d395b3ecaf4bf28c884f1dc7cf3459310d7c). Please [review the logs for more information](https://circleci.com/gh/dated/ark-explorer/935?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link).

_Once you've pushed the fixes, the build will automatically re-run. Thanks!_

**Comment by dated** [comment]
CircleCI and/or the API are behaving rather oddly today, some unit tests didn't even pass with a 30 second timeout, I'll restart these tomorrow.

**Comment by dated** [comment]
They passed eventually :wink:

**Comment by dated** [comment]
Looks like CryptoCompare has changed the conversion from BTC to ETH, I'll monitor if it changes back anytime soon and adjust the failing test otherwise.

```
"ConversionType": {
  "type": "multiply",
  "conversionSymbol": "ETH"
}
```

**Review by luciorubeens — APPROVED** [review]
Sounds good, thanks! And the conversion seems to have been normalized 👍

**Comment by ghost** [comment]
@dated A member has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by dated** [comment]
Yea it's back to BTC. I left the other value in place in case this happens again.

**Comment by ghost** [comment]
@dated Your pull request has been merged and marked as tier 4. _It will earn you $10 USD._

**Pull request merged**
