### PR TITLE
fix: truncation of block id

### PR DESCRIPTION
**Pull request by dated**
## Proposed changes

image

The div containing the block id was not truncated correctly, causing the buttons to misalign.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by ghost** [comment]
**Thanks for submitting this pull request!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
The [ci/circleci: test-node-stable](https://circleci.com/gh/dated/ark-explorer/1128?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link) job is failing as of [517396e917a60f97df521ae911fa6c6091ef9293](https://github.com/ArkEcosystem/explorer/commit/517396e917a60f97df521ae911fa6c6091ef9293). Please [review the logs for more information](https://circleci.com/gh/dated/ark-explorer/1128?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link).

_Once you've pushed the fixes, the build will automatically re-run. Thanks!_

**Comment by j-a-m-l** [comment]
@dated could you add a way to display it entirely (ie: tooltip, button to expand, etc.)?

**Review by j-a-m-l — APPROVED** [review]
Thanks, @dated.

**Comment by ghost** [comment]
A member has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by ghost** [comment]
Your pull request has been merged but was not assigned a bounty tier. A maintainer will assign a bounty tier to this pull request in the next few days.

**Comment by ghost** [comment]
Your pull request has been merged and marked as tier 4. _It will earn you $10 USD._

**Pull request merged**
