### PR TITLE
chore: add COSS wallet

### PR DESCRIPTION
**Pull request by dated**
## Proposed changes

Adds the COSS wallet.

## Types of changes

- [x] Other... Please describe: chore

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by ghost** [comment]
@dated Thanks for submitting this pull request, a maintainer will get back to you shortly!

**Comment by ghost** [comment]
@alexbarnsley @faustbrian @luciorubeens - please review this in the next few days. Be sure to explicitly select labels so I know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Review by j-a-m-l — APPROVED** [review]

**Comment by ghost** [comment]
@dated A member has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by j-a-m-l** [comment]
Thanks @dated

**Pull request merged**
