### PR TITLE
fix: base show-more condition on meta object

### LINKED ISSUE #811: bug: Better pagination for transactions
**Expected Behavior**

The transactions table of a wallet shouldn't display a "Show More" button if the total of transactions isn't > 25. Or, since the pagination now works properly, if the "next" attribute of the pagination is null.

**Current Behavior**

Currently, if you go on a wallet page (I guess it would be like that in other places too) with exactly 25 transactions, a "Show More" button will appear, and if you click on it, you'll see the page 2 of the transactions of that wallet, but with an empty content.

**Possible Solution**

Either fetch 26 transactions and only display 25 or use the pagination object.

### PR DESCRIPTION
**Pull request by dated**
## Summary

Fixes #811 by basing the condition of the show more button on the `meta.next` property.

Also fixes the pagination in MultiPayment transaction pages and slightly refactors the `getXCount` methods.

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [x] Ready to be merged

### CODE REVIEW

**Comment by ghost** [comment]
**Thanks for submitting this pull request!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Review by ItsANameToo — APPROVED** [review]

**Comment by ghost** [comment]
A member has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by ghost** [comment]
Your pull request has been merged but was not assigned a bounty tier. A maintainer will assign a bounty tier to this pull request in the next few days.

**Comment by ghost** [comment]
Your pull request has been merged and marked as tier 4. _It will earn you $20 USD._

**Pull request merged**
