### PR TITLE
Refreshes latest transactions #304

### PR DESCRIPTION
**Pull request by dated**

### CODE REVIEW

**Comment by faustbrian** [comment]
Could you please add tests for this change.

**Comment by dated** [comment]
Testing this will be difficult as there is no guarantee of new transactions for each new block. The fetching of the latest blocks however can be tested. Since both components use the same logic, we should be able to assume that that test validates this change as well. Or maybe you have an idea @ItsANameToo?

**Comment by ItsANameToo** [comment]
I agree that transactions will be difficult. Only possibility I can think of is looking into mocking the `getTransactions()` function and asserting that it gets called when network height changes, but not sure how and if it's possible 😬

**Comment by dated** [comment]
I have not come up with a solution for how to test this, other than indirectly through other tests that confirm the same behaviour. If someone wants to give it a shot, please do.

**Comment by dated** [comment]
Commit b5a795e seems to be missing in master, although being merged with #301

**Comment by faustbrian** [comment]
Merged it for now without tests passing as there seem to be other issues with the test suite.

**Comment by ItsANameToo** [comment]
wip

**Pull request merged**
