### PR TITLE
fix: transaction timestamp and vote count

### LINKED ISSUE #566: Invalid timestamps on transactions
https://i.imgur.com/5yI0nWN.jpg

---
This issue was created by `@vul`.

### PR DESCRIPTION
**Pull request by dated**
## Proposed changes

Fixes #566.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by ghost** [comment]
@dated Thanks for submitting this pull request, a maintainer will get back to you shortly!

**Comment by ghost** [comment]
@alexbarnsley @faustbrian @luciorubeens - please review this in the next few days. Be sure to explicitly select labels so I know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Review by faustbrian — APPROVED** [review]

**Comment by ghost** [comment]
@dated A contributor has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by ghost** [comment]
@dated Your pull request has been merged and marked as tier 4. _It will earn you $10 USD._

**Pull request merged**
