### PR TITLE
fix/refactor: delegate votercount and wallet search endpoint

### LINKED ISSUE #563: delegate voters count is incorrect
**Describe the bug**
The shown voters count of a delegate is incorrect. The old v1 api endpoint used to return ALL delegates in a single response, while the v2 api paginates the results.

### PR DESCRIPTION
**Pull request by dated**
## Proposed changes

Fixes #563, but without https://github.com/ArkEcosystem/core/pull/2103 the shown voters won't be fetched in the correct order.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] Refactoring (improve a current implementation without adding a new feature or fixing a bug)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by ghost** [comment]
@dated Thanks for submitting this pull request, a maintainer will get back to you shortly!

**Comment by ghost** [comment]
@alexbarnsley @faustbrian @luciorubeens - please review this in the next few days. Be sure to explicitly select labels so I know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by faustbrian** [comment]
Will leave this open until the core changes make it to master.

**Comment by ghost** [comment]
@faustbrian The [ci/circleci: test-node-stable](https://circleci.com/gh/dated/ark-explorer/893?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link) job is failing as of [85683beedf354fe72907d9c556a7948c8912e11d](https://github.com/ArkEcosystem/explorer/commit/85683beedf354fe72907d9c556a7948c8912e11d). Please [review the logs for more information](https://circleci.com/gh/dated/ark-explorer/893?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link).

_Once you've pushed the fixes, the build will automatically re-run. Thanks!_

**Comment by dated** [comment]
Closed in favor of #572.

**Comment by ghost** [comment]
@dated Your pull request has been closed, thank you for trying to solve an issue. If you think it was closed prematurely please provide additional information.

**Pull request closed without merging**
