### PR TITLE
chore: translation cleanup

### PR DESCRIPTION
**Pull request by dated**
## Proposed changes

Cleans up the translation files.

## Types of changes

- [x] Other... Please describe: translations

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes

## Further comments

The usual delegate search test has failed in the circleci build.

### CODE REVIEW

**Comment by faustbrian** [comment]
@dated conflicts

**Comment by dated** [comment]
> @dated conflicts

I see no conflict markers 🤔

**Comment by alexbarnsley** [comment]
Maybe he's saying you're a conflict :danstop:

**Comment by dated** [comment]
> Maybe he's saying you're a conflict :danstop:

Who knows :danbad:

**Review by faustbrian — APPROVED** [review]

**Pull request merged**
