### PR TITLE
fix(wallet): Refactor the UI for showing who the wallet is voting for

### PR DESCRIPTION
**Pull request by tpscrpt**
## Proposed changes

#550 

 - No changes for mobile
 - Add transaction table header div with "Voted {{delegate.name}}" (wallet-link)

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build (changes that affect the build system)
- [ ] Docs (documentation only changes)
- [ ] Test (adding missing tests or fixing existing tests)
- [ ] Other... Please describe:

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by tpscrpt** [comment]
vote-ui-fix

**Comment by tpscrpt** [comment]
I will fix the tests promptly

**Comment by tpscrpt** [comment]
I realize that the CircleCI tests will most likely fail due to the block tests. I have tested with up to 10 minutes and they still keep failing locally; I think this is the same for all devs atm.

I have nonetheless corrected the tests that my changes caused to fail.

**Comment by faustbrian** [comment]
Closing in favour of https://github.com/ArkEcosystem/explorer/pull/555.

**Pull request closed without merging**
