### PR TITLE
fix: use typeGroups in addition to type

### LINKED ISSUE #759: Refactor: use TypeGroup when checking tx types
With 2.6, `TypeGroups` are used in addition to the transaction types. Whenever we check for a specific transaction `type`, we should also assert that it is the correct `TypeGroup` so we don't end up with unexpected results. This is not done throughout all places where we check transaction types yet and needs to be improved.

### PR DESCRIPTION
**Pull request by ItsANameToo**
Resolves #759

### CODE REVIEW

**Comment by dated** [comment]
:hide:

**Comment by ItsANameToo** [comment]
what?

**Comment by ItsANameToo** [comment]
@alfonsobries some conflicts :hide:

**Comment by alfonsobries** [comment]
@ItsANameToo ✅

**Pull request merged**
