### PR TITLE
fix: remove border on last transaction asset property

### PR DESCRIPTION
**Pull request by dated**
## Summary

Do not set border on the last row of the magistrate asset details.

image

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [x] Ready to be merged

### CODE REVIEW

**Comment by ghost** [comment]
**Thanks for submitting this pull request!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by dated** [comment]
Unrelated failures, can you retrigger the tests @itsanametoo?

**Comment by ItsANameToo** [comment]
🤔 seems the checkout is messed up now, might be due to the style commit. Will take a closer look after your other PR

**Comment by dated** [comment]
The eslint workflow pulls the correct branch
```
git checkout --progress --force refs/remotes/pull/883/merge
```
the test workflows somehow are stuck on a bad
```
git checkout --progress --force 2dc6f8acf16a0f7fb4f1e14ebc63a38a99ddd77f
```

🤷‍♂

**Comment by dated** [comment]
The GitHub UI didn't even give me the option to update the branch right now, so there might have been something messy internally. I merged manually and the refs seem to be in order again.

**Comment by ItsANameToo** [comment]
Yeah I didn't have the button either

**Review by ItsANameToo — APPROVED** [review]

**Comment by ghost** [comment]
A member has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by ghost** [comment]
Your pull request has been merged. Thank you for your contribution to the ARK Ecosystem.

**Pull request merged**
