### PR TITLE
ci: trigger workflows for push.* and pull_request.* events

### PR DESCRIPTION
**Pull request by faustbrian**
A summary of what changes this PR introduces and why they were made.

## What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Refactor
- [ ] Performance
- [ ] Tests
- [ ] Build
- [ ] Documentation
- [ ] Code style update
- [ ] Continuous Integration
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Does this PR release a new version?

- [ ] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `develop` branch, _not_ the `master` branch
- [ ] All tests are passing
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by ItsANameToo** [comment]
@alexbarnsley how to test

**Comment by alexbarnsley** [comment]
@ItsANameToo excellent question. Add the below to `.env`, then change the currency in the navbar settings dropdown:

```
EXPLORER_NETWORK_CAN_BE_EXCHANGED=true
EXPLORER_NETWORK_CURRENCY="ARK"
```

image

There is still a size issue when using crypto - I believe this is handled in another task isn't it?

**Comment by alexbarnsley** [comment]
:sweating:

**Comment by alexbarnsley** [comment]
Should be done @ItsANameToo

**Pull request merged**
