### PR TITLE
chore: prepare new network config 🎉

### PR DESCRIPTION
**Pull request by criptolot**
A summary of what changes this PR introduces and why they were made.

## What kind of change does this PR introduce?

- [x] Bugfix
- [x] Feature
- [x] Refactor
- [x] Performance
- [x] Tests
- [x] Build
- [x] Documentation
- [x] Code style update
- [x] Continuous Integration
- [x] Other, please describe:

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

## Does this PR release a new version?

- [x] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `develop` branch, _not_ the `master` branch
- [x] All tests are passing
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by ghost** [comment]
**Thanks for submitting this pull request!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by criptolot** [comment]
New Network Explorer ARK Fork

**Comment by ghost** [comment]
Your pull request has been closed, thank you for trying to solve an issue. If you think it was closed prematurely please provide additional information.

**Comment by ghost** [comment]
The [ci/circleci: test-node-11](https://circleci.com/gh/ArkEcosystem/explorer/947?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link) job is failing as of [51e7d438adbc962c1b7dfda3b53fdd14fe15e891](https://github.com/ArkEcosystem/explorer/commit/51e7d438adbc962c1b7dfda3b53fdd14fe15e891). Please [review the logs for more information](https://circleci.com/gh/ArkEcosystem/explorer/947?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link).

_Once you've pushed the fixes, the build will automatically re-run. Thanks!_

**Comment by ghost** [comment]
The [ci/circleci: test-node-12](https://circleci.com/gh/ArkEcosystem/explorer/946?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link) job is failing as of [51e7d438adbc962c1b7dfda3b53fdd14fe15e891](https://github.com/ArkEcosystem/explorer/commit/51e7d438adbc962c1b7dfda3b53fdd14fe15e891). Please [review the logs for more information](https://circleci.com/gh/ArkEcosystem/explorer/946?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link).

_Once you've pushed the fixes, the build will automatically re-run. Thanks!_

**Pull request closed without merging**
