### PR TITLE
refactor: make menu components dry

### PR DESCRIPTION
**Pull request by dated**
## Summary

These changes reduce boilerplate in the menu components by providing the respective entries from the parent `AppHeader` component, which makes the addition or removal of any future menu entries more straightforward.

This PR also includes some small UI fixes:

- fixes the border on the "Advanced Search" menu entry on mobile views
- moves the margin of the half-width input fields to the parent container, so that both inputs actually have the same width

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [x] Ready to be merged

### CODE REVIEW

**Comment by ghost** [comment]
**Thanks for submitting this pull request!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Review by ItsANameToo — APPROVED** [review]

**Comment by ghost** [comment]
A member has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by ghost** [comment]
Your pull request has been merged and marked as tier 4. _It will earn you $20 USD._

**Comment by ItsANameToo** [comment]
@alfonsobries the navbar is supposed to be 84px in height, so if it's different in the design then the design is incorrect

**Comment by ItsANameToo** [comment]
@alfonsobries I don't see anything about the navbar in the clickup task you linked 🤔 (https://app.clickup.com/t/m59ftw)

**Comment by alfonsobries** [comment]
@ItsANameToo oops wrong link https://app.clickup.com/t/3uwpvx even with the 84px the margin below the navbar needs to be adjusted (it's cropping like 2px from the status section). Im on it

**Comment by alfonsobries** [comment]
@ItsANameToo ✅

**Pull request merged**
