### PR TITLE
refactor: spacing better rank

### PR DESCRIPTION
**Pull request by whitehat**
## Proposed changes

Add Spacing For Rank. Cherrypicked From #474.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build (changes that affect the build system)
- [ ] Docs (documentation only changes)
- [ ] Test (adding missing tests or fixing existing tests)
- [ ] Other... Please describe:

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by alexbarnsley — APPROVED** [review]
Thanks! 👌

**Comment by boldninja** [comment]
@whitehat Can you provide me with your ARK address for GitHub bounty? You can also contact me on ARK's Slack - https://ark.io/slack (username : boldninja) and direct message me your address there.

**Comment by whitehat** [comment]
Hello @boldninja. Please Can Send To AdSnR4KAA6DCMr96gEZhB744sFBpw6Qk19. Thankyou

**Comment by boldninja** [comment]
Distributed.

**Comment by whitehat** [comment]
Thankyou @boldninja.

**Pull request merged**
