### PR TITLE
feat: show the name of known addresses on the wallet page

### PR DESCRIPTION
**Pull request by j-a-m-l**
## Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Checklist
- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by ghost** [comment]
The [ci/circleci: test-node-stable](https://circleci.com/gh/ArkEcosystem/explorer/746?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link) job is failing as of [9d3c8d5fa6e523355ccf412460f7ed01ed4c0a4e](https://github.com/ArkEcosystem/explorer/commit/9d3c8d5fa6e523355ccf412460f7ed01ed4c0a4e). Please [review the logs for more information](https://circleci.com/gh/ArkEcosystem/explorer/746?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link).

_Once you've pushed the fixes, the build will automatically re-run. Thanks!_

**Comment by dated** [comment]
In case others are wondering how this will look like:

image

**Review by luciorubeens — APPROVED** [review]

**Review by dated — CHANGES_REQUESTED** [review]
Needs adjustments for the mobile view.

**Comment by j-a-m-l** [comment]
What adjustment, @dated?

**Comment by dated** [comment]
Or is it intended like this? Feels a bit "off".

image

**Comment by j-a-m-l** [comment]
Yes, I didn't include the icon on mobile on purpose, but I'm all ears, @dated.

**Comment by dated** [comment]
All good :+1: It would feel more balanced without the extra third line, but I will rework the mobile view sometime soon probably, to get rid of the empty quadrants (when there is no public key or no vote) which have always bugged me 😂

**Comment by j-a-m-l** [comment]
:ok_hand:

**Pull request merged**
