### PR TITLE
improves #252 to not add the empty div if no tx has a smartbridge

### PR DESCRIPTION
**Pull request by dated**

### CODE REVIEW

**Comment by ItsANameToo** [comment]
:+1:

**Comment by dated** [comment]
i'm not getting this out of my head :D how about filled icon if smartbridge is present, unfilled if not?

image

**Comment by ItsANameToo** [comment]
Hmm, that's also a possibility. Looks cool and solves the marging issues so I'd say go for it :D

**Comment by dated** [comment]
thanks for the feedback!

**Pull request merged**
