### PR TITLE
Add LiteBit to Mainnet known wallets

### PR DESCRIPTION
**Pull request by j-a-m-l**

### CODE REVIEW

**Comment by boldninja** [comment]
Address is same as Bittrex. LiteBit is using Bittrex to buy at market price and sends back to user probably.

**Comment by j-a-m-l** [comment]
Lol, then this isn't needed.

**Comment by faustbrian** [comment]
Should we change it to Bittrex / LiteBit then?

**Comment by j-a-m-l** [comment]
I wouldn't do it because the real owner of the wallet is Bittrex and adding LiteBit would be inaccurate.

**Pull request closed without merging**
