### PR TITLE
refactor: tidying mobile spacing

### PR DESCRIPTION
**Pull request by whitehat**
## Proposed changes

Add / Remove Unneeded Spacing For Mobile Screen

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build (changes that affect the build system)
- [ ] Docs (documentation only changes)
- [ ] Test (adding missing tests or fixing existing tests)
- [ ] Other... Please describe:

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by dated** [comment]
i will look these through one by one later today. if you can give a general reason why the paddings are 'unneeded' that'd be great. whitespace is a design element.

here's an example of where one of the changes breaks the look and feel:

image

**Comment by whitehat** [comment]
Purpose Was Try To Match Spacing. There Were Some Areas Had Too Much Spacing Above And Not Below.. Etc. Will Review Myself Tomorrow Afternoon As 3 AM Here, Make Sure I Not Caused More Issues Like Your Screen Shot. Thank You

**Comment by whitehat** [comment]
Hello @dated. Did You Get Round To Having Look? Thankyou

**Comment by dated** [comment]
still needs some work :)

`src/components/block/Transactions.vue`

image

personally i think that most of these changes lead to a pretty squashed design, the one change i appreciate is where you add whitespace actually (the rank columns). again, this is my personal opinion.

i'll leave the decision to the designer.

**Comment by whitehat** [comment]
Hello @dated. Appreciate Your Feedback. Could Leave All Changes Apart From Rank Spacing If You Would Prefer? I Don't Mind.. Changes Were More To Be Consistent Where Top Right Bottom Left Spacing Was Same On Mobile. Please Let Me Know If Continue Or Just Do Rank Spacing. Thankyou

**Comment by faustbrian** [comment]
Those changes make the layout look very cramped. If you only change the rank spacing we can merge this.

**Comment by whitehat** [comment]
Hello. Have Cherrypicked Rank Commit To New PR #485. Please Have A Look. Thankyou

**Pull request closed without merging**
