### PR TITLE
feat: save chart period in store and local storage

### PR DESCRIPTION
**Pull request by dated**
## Proposed changes

Stores the currently selected period of the price chart so it does not reset on every page change.

## Types of changes

- [x] New feature (non-breaking change which adds functionality)
- [x] Refactoring (improve a current implementation without adding a new feature or fixing a bug)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by ghost** [comment]
@dated Thanks for submitting this pull request, a maintainer will get back to you shortly!

**Comment by ghost** [comment]
@alexbarnsley @faustbrian @luciorubeens - please review this in the next few days. Be sure to explicitly select labels so I know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
@dated The [ci/circleci: test-node-stable](https://circleci.com/gh/dated/ark-explorer/959?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link) job is failing as of [ee40d17c836e1033483b1a2486b27fa64eba7944](https://github.com/ArkEcosystem/explorer/commit/ee40d17c836e1033483b1a2486b27fa64eba7944). Please [review the logs for more information](https://circleci.com/gh/dated/ark-explorer/959?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link).

_Once you've pushed the fixes, the build will automatically re-run. Thanks!_

**Review by luciorubeens — APPROVED** [review]
Sounds good to me 👍

**Comment by ghost** [comment]
@dated A member has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by luciorubeens** [comment]
@dated Unit tests failing after updating the branch

**Comment by dated** [comment]
The usual jest timeouts... They passed now, will switch to green in ~8 minutes.

**Comment by ghost** [comment]
@dated Your pull request has been merged and marked as tier 3. _It will earn you $25 USD._

**Pull request merged**
