### PR TITLE
fix: use break-word for smartbridge instead of break-all

### PR DESCRIPTION
**Pull request by ItsANameToo**
~~Changes `break-all`  to `break-word` so we break regular words in a logical location~~

Changes the `break-word` stuff to `truncate` instead; giving the smartbridge column a fixed width on different sizes. Also remove smartbridge starting at `< 1100px` width, since it would otherwise push the fee column out until the smartbridge field would be removed at `< 1024px` width.

### CODE REVIEW

**Comment by zillionn** [comment]
Will this break long URLs?

**Comment by ItsANameToo** [comment]
@alexbarnsley can you take a look at this when you have the time?

**Comment by ItsANameToo** [comment]
@zillionn it truncates long urls, so you'll just see the first part of it

**Review by faustbrian — APPROVED** [review]

**Comment by ghost** [comment]
The [ci/circleci: test-node-10](https://circleci.com/gh/ArkEcosystem/explorer/839?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link) job is failing as of [47b5753cd2c3ee038241e84125d74c1b050ed8b4](https://github.com/ArkEcosystem/explorer/commit/47b5753cd2c3ee038241e84125d74c1b050ed8b4). Please [review the logs for more information](https://circleci.com/gh/ArkEcosystem/explorer/839?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link).

_Once you've pushed the fixes, the build will automatically re-run. Thanks!_

**Comment by faustbrian** [comment]
@alexbarnsley conflicts

**Comment by alexbarnsley** [comment]
updated @faustbrian, thanks

**Pull request merged**
