### PR TITLE
feat: show vote count and percentage

### LINKED ISSUE #600: Show Vote Weight in Column Instead of Tooltip
Currently Delegate Monitor shows voting weight in a tooltip like this:

image

But because the vote weight is a highly sought-after piece of information when looking at delegate lists, it would be better to give it its own column. This would finally deprecate https://explorer.ark.io/VoteReport.txt which is currently preferable due to a global view of all vote weights.

There seems to be definitely enough space to implement the additional column, to the right of vote percent. I would really appreciate it, thanks!

### PR DESCRIPTION
**Pull request by dated**
## Proposed changes

Closes #600.

## Types of changes

- [x] Refactoring (improve a current implementation without adding a new feature or fixing a bug)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by ghost** [comment]
**Thanks for submitting this pull request!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by j-a-m-l** [comment]
@dated I'd keep the percentage of votes near the number of votes.

**Comment by dated** [comment]
image

**Comment by ghost** [comment]
The [ci/circleci: test-node-stable](https://circleci.com/gh/dated/ark-explorer/1110?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link) job is failing as of [e11a0449dbb5a4ad3b8d690117ee659ef4853253](https://github.com/ArkEcosystem/explorer/commit/e11a0449dbb5a4ad3b8d690117ee659ef4853253). Please [review the logs for more information](https://circleci.com/gh/dated/ark-explorer/1110?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-build-link).

_Once you've pushed the fixes, the build will automatically re-run. Thanks!_

**Review by j-a-m-l — COMMENTED** [review]
@dated, works flawlessly, but, I've a suggestion: what do you think about changing the style of the percentage (smaller font, using grey, etc.) to make it less noisy?

**Review by j-a-m-l — APPROVED** [review]
:ok_hand: @dated. Thanks.

**Comment by ghost** [comment]
A member has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by ghost** [comment]
Your pull request has been merged and marked as tier 3. _It will earn you $25 USD._

**Comment by ItsANameToo** [comment]
@faustbrian test coverage

**Comment by ItsANameToo** [comment]
ftfy @faustbrian :bleh:

**Pull request merged**
