### PR TITLE
User can now choose a custom API server (see issue #324)

### PR DESCRIPTION
**Pull request by Neurone**
- Setting is saved to local storage for later use
- User can reset to the original value

### CODE REVIEW

**Comment by faustbrian** [comment]
Running an explorer on normal nodes can have a major impact on performance, that is why the https://github.com/ArkEcosystem/ark-node/tree/explorer branch exists.

With this feature everyone could just put in any IP and cause performance issues for nodes. I will have to think about merging this.

**Comment by Neurone** [comment]
I didn't get it: you can find the exactly same feature - changing the node you connect to - in the Desktop Wallet and in the Mobile Wallet.

And frankly you scared me a bit with this answer: are you really saying that having this simple feature **at client side** can put any ARK node at risk? If so, it means that **ARK nodes are already at risk of spam attacks**, with or without this feature, and then we have major problems to think about and to solve in the core.

Connecting to an exposed node cannot be considered in any case a bad behaviour: a client should not be able to ever put a node at risk, not because the client acts _fairly_ but because the node must protect itselft by attacks in different ways.

I didn't got a full node up and running yet, but I thought this kind of APIs - let's call them a sort of analytics API - were exposed only by owner's will, didn't they? Core v2 already address this kind of common issues for API exposition (listening only on loopback interface, access control, blacklisting client's considered spammers, throttling, etc.)? If not, I think these issues must be addressed before going live to the Mainnet with the v2.

**Comment by faustbrian** [comment]
The issue is more on the performance side with low-spec servers as the database has millions of records which can put a lot of strain on those servers with low-specs and the explorer produces a whole lot more traffic then a wallet.

All of those issues have been addresses with v2 but currently v1 is on mainnet, not v2.

**Comment by faustbrian** [comment]
I will close this for now and revisit it when v2 is on mainnet. Thanks for the PR though.

**Pull request closed without merging**
